### ISSUE TITLE
rgb_to_cie gamma

### ISSUE THREAD

**Issue by ghost** [usolved/cie-rgb-converter#1]
Shouldn't it be pow(color,2.2) for sRGB data?

**Comment by usolved** [comment]
Thanks for the feedback.

I'm by no means an expert with sRGB color correction. But from what I understand there's no right or wrong. It depends on the viewing environments when to choose 2.2 or 2.4.

I find this article really helpful in understanding the different gamma correction values:
https://mixinglight.com/color-tutorial/gamma-2-2-vs-gamma-2-4-davinci-resolve/

For example when you have a darker room with a tablet on your wall where the colors are displayed then 2.4 is properly the better value. In a light office environment 2.2 would be better.

So I'm not quite sure what the default should be since it really depends on the use case :).
